#+title: Renovation concepts
#+filetags:

Dear architect,

I want to renovate my home and I'm potentially interested in hiring you to help me design the renovation, drawing the plans and interfacing with the municipality to check what's possible to build. I also don't have a strong preference yet about which contractor to hire, so I'd be open to consider any referral from your network if you think they'd be a good fit.

I want to do something creative and interesting with my home.

* Current situation

The neighbourhood was build in the 1970s and it consists of a mixture of one, two and three story flat-roofed houses; with a significant number of one and two story houses having a rooftop extension. My house is at the corner of a row of single-story terraced houses. The current layout is the original, the side walls are made of concrete and coarse gravel, and all interior walls are non-structural.

#+CAPTION: diagram of the current layout
#+NAME: current
[[../media/planta_og.svg]]

The main windows to the serra/garden are new, triple glazing, same as the skylight. All other windows are double glazing from the 90s.

* Renovation design goals

I want to build a rooftop extension and remodel the current ground floor.

** Priorities
1. Office/studio room in the top floor with a high degree of sound insulation with the neighbours' house. The goal is to be able to make music at night without bothering the neighbours.
2. Kitchen with plenty natural light.
3. Top floor bathroom with natural light and ventilation. Ideally wall windows, a skylight could be a compromise.

** Nice to have

1. Ground floor bathroom with natural light and ventilation.
2. All-electric energy system with a heat pump (+ supplementary on-demand water heating?)

* Layout design

There are two big unknowns about what the municipality will permit:  how large can the extension be, and how many side windows are possible to include in the top floor---or open in the ground floor.

** Extension
A very experienced contractor that has built over a dozen rooftop extensions in my neighbourhood insists that the municipality asks for 0.5m clearance between the current facade and the extension facade on my street. However, my next-door neighbours told me that the municipality told their architect that they needed ~3m clearance on the front facade, and that's the specification they used to build their extension. I'd like the extension to be as big as possible, but I think the most likely reality is that we would need to design the extension with the largest clearance.

In the ideal case that the extension floor plan only needs 0.5m facade clearance, [[long][Figure 2]] is how I'm imagining the extension layout, with an open mind about how to do the central stairs area.

#+CAPTION: ideal top floor, with the large extension
#+NAME: long
[[../media/planta_top_long.svg]]

If the extension needs 3m clearance on the front facade, [[short][Figure 3]]
is where I'm at in terms of layout design.

#+CAPTION: top floor with the smaller extension
#+NAME: short
[[../media/planta_top_short.svg]]

My rationale for placing the bathroom in that side of the house is for the possibility of having a side window opening to the street. I'm not sure how realistic is to have the bathroom in that location giving that the plumbing of the current bathroom is on the other side of the house. If the municipality won't allow including a bathroom window, or the plumbing is too inconvenient, I'd be willing to build the bathroom in the opposite side and include a skylight.

I want the top floor bathroom to include a shower, sink, toilet and bidet, regardless of the extension size.

** Ground floor

I think the design of the ground floor will fall into place once there's clarity about what's possible with the extension; but I'm planning on taking down all existing walls, redoing the electrical system, and taking out the current gas and heating pipes.

The "back" garden entrance is used as the main entrance to the home, so I want to "front" entrance to open directly to the ground floor studio / bedroom to maximize space.

The current size of the kitchen and living area feels perfect, so I'm not interested in making that room bigger, unless the stairs are included in it.

Right now the kitchen has great natural light and ventilation because of the skylight above it, which will be gone after building the extension. That's why I'm thinking about moving it to the street-side to place it next to the window, which would mean having the hallway door in the neighbours-side.

I want to maintain a fully functional ground floor bathroom with a shower, sink and toilet; but with smaller dimensions than the currently existing one.

#+CAPTION: new ground floor layout diagram
[[../media/planta_ground_new.svg]]

* Building method

A popular option on my neighbourhood are these guys: https://www.veerhuis.eu/ . They use metal frames that are build off-site and expanded polystyrene walls. It seems to cost slightly higher than a more traditional build, but with a faster built time and a higher insulation value.

I don't have strong opinions and I'm open to standard methods or alternatives.

* Interior design
- concrete floors, underfloor heating, warm white walls
- stainless steel kitchen and fixtures
- 30x30 white tiles, with non-white grout
- cork paneling and furniture, doors
- glass blocks
- no ceiling lights, all dimmable
