(setq make-backup-files nil)
(load (expand-file-name "org-static-blog.el" (file-name-directory
                                              load-file-name)))
(load (expand-file-name "htmlize.el" (file-name-directory
                                      load-file-name)))
(load (expand-file-name "hacks.el" (file-name-directory
                                    load-file-name)))

(unpackaged/org-export-html-with-useful-ids-mode)

(setq org-html-htmlize-output-type 'css
      org-html-htmlize-font-prefix "htmlize-"
      org-html-head-include-default-style nil)

(defun coba-file-content-as-string (filename)
  "Return the contents of FILENAME as string.
    https://gist.github.com/bigodel/56a4627afdfe9ad28f6dcc68b89a97f8"
  (with-temp-buffer
    (insert-file-contents filename)
    (buffer-string)))

(setq org-static-blog-publish-title "Coba")

(setq org-static-blog-publish-url ".")

(setq coba-org-static-blog-actual-publish-url "https://cobac.eu/")

(setq org-static-blog-publish-directory "public/")

(setq org-static-blog-posts-directory "posts/")

(setq org-static-blog-drafts-directory "drafts/")

(setq org-static-blog-archive-file "posts.html")

(setq org-static-blog-enable-tags t)

(setq org-export-with-toc nil)

(setq org-static-blog-enable-og-tags t)

(setq org-export-with-section-numbers nil)

(setq org-static-blog-index-length 0)

(setq org-static-blog-use-preview t)

(setq org-static-blog-texts
      '((other-posts
         ("coba" . ""))
        (date-format
         ("coba" . "%Y-%m-%d"))
        (tags
         ("coba" . ""))
        (archive
         ("coba" . ""))
        (posts-tagged
         ("coba" . ""))
        (no-prev-post
         ("coba" . "There is no previous post"))
        (no-next-post
         ("coba" . "There is no next post"))
        (title
         ("coba" . "Title: "))
        (filcobaame
         ("coba" . "Filename: "))))

(setq org-static-blog-langcode "coba")

(setq org-static-blog-page-header (coba-file-content-as-string "morsels/header.html"))

(setq org-static-blog-page-preamble (coba-file-content-as-string "morsels/preamble.html"))

(setq org-static-blog-page-postamble (coba-file-content-as-string "morsels/postamble.html"))

(defun org-static-blog-post-preamble (post-filename)
  "Returns the formatted date and headline of the post.
This function is called for every post and prepended to the post body.
Modify this function if you want to change a posts headline."
  (concat
   org-static-blog-post-preamble-text
   "<div class=\"title-with-tags\">\n"
   "<h1 class=\"post-title\">"
   "<a href=\"" (org-static-blog-get-post-url post-filename) "\">"
   (org-static-blog-get-title
    post-filename)
   "</a>"
   "</h1>\n"
   "<div class=\"taglist\">\n"
   (org-static-blog-post-taglist post-filename)
   "</div>\n"
   "</div>\n"
   (when (org-static-blog-get-date
          post-filename)
     (concat
      "<div class=\"post-date\">\n" "~ "
      (format-time-string
       (org-static-blog-gettext
        'date-format)
       (org-static-blog-get-date
        post-filename))))
   "</div>"))

(defun org-static-blog-post-postamble (post-filename)
  "Returns the tag list and comment box at the end of a post.
This function is called for every post and the returned string is
appended to the post body, and includes the tag list generated by
followed by the HTML code for comments."
  (concat ""
          (if
              (or (string= org-static-blog-post-comments "")
                  (member org-static-blog-no-comments-tag
                          (org-static-blog-get-tags
                           post-filename)))
              ""
            (concat "\n<div id=\"comments\">"
                    org-static-blog-post-comments
                    "</div>"))
          org-static-blog-post-postamble-text))

(defun org-static-blog-get-date (post-filename)
  "Extract the `#+date:` from POST-FILENAME as date-time."
  (let ((case-fold-search t))
    (with-temp-buffer
      (insert-file-contents post-filename)
      (goto-char (point-min))
      (if (search-forward-regexp
           "^\\#\\+date:[ ]*[[<]?\\([^]>]+\\)[]>]?$" nil t)
          (date-to-time (match-string 1))))))

(defun org-static-blog-assemble-archive ()
  "Re-render the blog archive page.
The archive page contains single-line links and dates for every
blog post, but no post body."
  (let ((archive-filename (concat-to-dir
                           org-static-blog-publish-directory
                           org-static-blog-archive-file))
        (archive-entries nil)
        (post-filenames (org-static-blog-get-post-filenames)))
    (setq post-filenames (sort post-filenames (lambda (x y) (time-less-p
                                                             (org-static-blog-get-date y)
                                                             (org-static-blog-get-date x)))))
    (org-static-blog-with-find-file
     archive-filename
     (org-static-blog-template
      org-static-blog-publish-title
      (concat
       "<ul>\n"
       (apply 'concat (mapcar 'org-static-blog-get-post-summary
                              post-filenames))
       "</ul>\n")))))

(defun org-static-blog-get-post-summary (post-filename &optional
                                                       no-tags)
  "Assemble post summary for an archive page.
This function is called for every post on the archive and
tags-archive page. Modify this function if you want to change an
archive headline."
  (let ((taglist (org-static-blog-post-taglist post-filename)))
    (concat
     "<li>\n"
     "<span class=\"post-date\">\n"
     (format-time-string (org-static-blog-gettext 'date-format)
                         (org-static-blog-get-date post-filename))
     "</span>"
     " ~ <a class=\"post-title-inline\" href=\"" (org-static-blog-get-post-url
                                                  post-filename) "\">"
     (org-static-blog-get-title
      post-filename)
     "</a>\n"
     (unless no-tags
       (when (and taglist (not (string-empty-p taglist)))
         (concat
          "~"
          "<span class=\"taglist\">"
          taglist
          "</span>")))
     "</li>\n")))

(defun org-static-blog-post-taglist (post-filename)
  "Returns the tag list of the post.
This part will be attached at the end of the post, after
the taglist, in a <div id=\"taglist\">...</div> block."
  (let ((taglist-content "")
        (tags
         (remove org-static-blog-no-comments-tag
                 (remove org-static-blog-rss-excluded-tag
                         (org-static-blog-get-tags post-filename)))))
    (when (and tags org-static-blog-enable-tags)
      (setq taglist-content
            (mapconcat (lambda (tag)
                         (concat "\n<a href=\""
                                 (org-static-blog-get-absolute-url (concat "tags.html#" (downcase tag)))
                                 "\">" tag "</a>"))
                       tags "")))
    taglist-content))

(defun org-static-blog-assemble-tags ()
  "Render the tag archive and tag pages."
  (org-static-blog-assemble-tags-archive))

(defun org-static-blog-assemble-tags-archive ()
  "Assemble the blog tag archive page.
The archive page contains single-line links and dates for every
blog post, sorted by tags, but no post body."
  (let ((tags-archive-filename (concat-to-dir
                                org-static-blog-publish-directory
                                org-static-blog-tags-file))
        (tag-tree (org-static-blog-get-tag-tree)))
    (setq tag-tree (sort tag-tree (lambda (x y) (string-greaterp (car y) (car x)))))
    (org-static-blog-with-find-file
     tags-archive-filename
     (org-static-blog-template
      org-static-blog-publish-title
      (concat
       (apply 'concat (mapcar
                       'org-static-blog-assemble-tags-archive-tag
                       tag-tree)))))))

(defun org-static-blog-assemble-tags-archive-tag (tag)
  "Assemble single TAG for all filenames."
  (let ((post-filenames (cdr tag)))
    (setq post-filenames
          (sort post-filenames (lambda (x y) (time-less-p (org-static-blog-get-date y)
                                                          (org-static-blog-get-date x)))))
    (concat "<li>" "<span class=\"tag-title\" id=\"" (downcase (car
                                                                tag))
            "\">" (downcase (car tag))
            "</span>\n<ul>\n"
            (apply 'concat (mapcar '(lambda (post-filenames)
                                      (org-static-blog-get-post-summary
                                       post-filenames 'no-tags))
                                   post-filenames))"</ul>\n</li>")))

(defun org-static-blog-assemble-multipost-page (pub-filename
                                                post-filenames &optional front-matter)
  "Assemble a page that contains multiple posts one after another.
Posts are sorted in descending time."
  (setq post-filenames (sort post-filenames (lambda (x y) (time-less-p (org-static-blog-get-date y)
                                                                       (org-static-blog-get-date x)))))
  (org-static-blog-with-find-file
   pub-filename
   (org-static-blog-template
    org-static-blog-publish-title
    (concat
     (when front-matter front-matter)
     (apply 'concat (mapcar
                     (if org-static-blog-use-preview
                         'org-static-blog-get-preview
                       'org-static-blog-get-post-content)
                     post-filenames))))))

;; patched with a default-directory to allow relative paths with babel outputs
(defun org-static-blog-render-post-content (post-filename)
  (let ((org-html-doctype "html5")
        (org-html-html5-fancy t)
        (post-filename-abs (expand-file-name post-filename)))
    (save-excursion
      (let ((current-buffer (current-buffer))
            (buffer-exists (org-static-blog-file-buffer post-filename))
            (result nil))
        (with-temp-buffer
          (if buffer-exists
              (insert-buffer-substring buffer-exists)
            (insert-file-contents post-filename-abs))
          (setq default-directory (file-name-directory post-filename-abs))
          (org-mode)
          (goto-char (point-min))
          (org-map-entries
           (lambda ()
             (setq org-map-continue-from (point))
             (org-cut-subtree))
           org-static-blog-no-post-tag)
          (setq result
                (org-export-as 'org-static-blog-post-bare nil nil nil nil))
          (switch-to-buffer current-buffer)
          result)))))

(setopt org-confirm-babel-evaluate nil)

(org-babel-do-load-languages
 'org-babel-load-languages '((dot . t)))

(setopt org-html-footnotes-section
  "<div id=\"footnotes\">
  <!-- I <3 %s -->
<div id=\"text-footnotes\">
%s
</div>
</div>")

(defun org-static-blog-get-rss-item (post-filename)
  "Overwriten coba-org-static-blog-actual-publish-url."
  (let ((post-url (url-encode-url
                   (concat-to-dir coba-org-static-blog-actual-publish-url
                                  (org-static-blog-get-post-public-path post-filename)))))
    (concat
     "<item>\n"
     "  <title><![CDATA[" (org-static-blog-get-title post-filename) "]]></title>\n"
     "  <description><![CDATA["
     (org-static-blog-get-post-content post-filename t)
     "]]></description>\n"
     (let ((categories ""))
       (when (and (org-static-blog-get-tags post-filename) org-static-blog-enable-tags)
         (dolist (tag (org-static-blog-get-tags post-filename))
           (setq categories (concat categories
                                    "  <category><![CDATA[" tag "]]></category>\n"))))
       categories)
     "  <link>" post-url "</link>\n"
     "  <guid>" post-url "</guid>\n"
     "  <pubDate>"
     (let ((system-time-locale "C"))
       (format-time-string "%a, %d %b %Y %H:%M:%S %z" (org-static-blog-get-date post-filename)))
     "</pubDate>\n"
     "</item>\n")))

(defun org-static-blog--write-rss (items &optional tag)
  "Generates an RSS file for the given TAG, or for all tags is TAG is nil. Overwriten coba-org-static-blog-actual-publish-url."
  (let ((title (format "%s%s"
                       org-static-blog-publish-title
                       (if tag (concat " - " tag) "")))
        (url (format "%s%s"
                     coba-org-static-blog-actual-publish-url
                     (if tag (concat "/tag-" (downcase tag) ".html") "")))
        (items (sort items (lambda (x y) (time-less-p (car y) (car x))))))
    (org-static-blog-with-find-file
     (org-static-blog--rss-filename tag)
     (concat "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
	           "<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">\n"
	           "<channel>\n"
	           "<title><![CDATA[" title "]]></title>\n"
	           "<description><![CDATA[" title "]]></description>\n"
	           "<link>" url "</link>\n"
	           "<lastBuildDate>" (let ((system-time-locale "C")) ; force dates to render as per RSS spec
				                         (format-time-string "%a, %d %b %Y %H:%M:%S %z" (current-time)))
             "</lastBuildDate>\n"
             org-static-blog-rss-extra
	           (apply 'concat (mapcar 'cdr (org-static-blog--prune-items items)))
	           "</channel>\n"
	           "</rss>\n"))))

(defun org-static-blog-assemble-index ()
  "Generates variants of `index-xx.html', each of them with different content from `moresels/root-variants'.
   Each root variant ends up in approximately the same proportion of `index-xx.html' files,
   with the idea that the webserver serves a random one as the root `index.html' each time."
  (let* ((n-slots 60)
         (variants-dir "morsels/root-variants")
         (variants (sort (directory-files variants-dir t "\\.html\\'")
                         #'string<))
         (n (length variants))
         (post-filenames (sort (org-static-blog-get-post-filenames)
                               (lambda (x y)
                                 (time-less-p (org-static-blog-get-date x)
                                              (org-static-blog-get-date y))))))
    (when (zerop n)
      (error "No variants found in %s" variants-dir))
    (dotimes (i n-slots)
      (let ((front-matter (coba-file-content-as-string
                           (nth (mod i n) variants)))
            (out-path (concat-to-dir
                       org-static-blog-publish-directory
                       (format "index-%02d.html" i))))
        (org-static-blog-assemble-multipost-page
         out-path
         (last post-filenames org-static-blog-index-length)
         front-matter)))
    (message "Filled %d slots from %d variants in public/index-NN.html"
             n-slots n)))

(org-static-blog-publish t)
