(setq make-backup-files nil)
(load (expand-file-name "org-static-blog.el" (file-name-directory
                                              load-file-name)))


(load (expand-file-name "htmlize.el" (file-name-directory
                                      load-file-name)))
(setq org-html-htmlize-output-type 'css
      org-html-htmlize-font-prefix "htmlize-"
      org-html-head-include-default-style nil)

(defun coba-file-content-as-string (filename)
  "Return the contents of FILENAME as string.
    https://gist.github.com/bigodel/56a4627afdfe9ad28f6dcc68b89a97f8"
  (with-temp-buffer
    (insert-file-contents filename)
    (buffer-string)))

(setq org-static-blog-publish-title "Coba")

(setq org-static-blog-publish-url ".")

(setq org-static-blog-publish-directory "public/")

(setq org-static-blog-posts-directory "posts/")

(setq org-static-blog-drafts-directory "drafts/")

(setq org-static-blog-archive-file "posts.html")

(setq org-static-blog-enable-tags t)

(setq org-export-with-toc nil)

(setq org-static-blog-enable-og-tags t)

(setq org-export-with-section-numbers nil)

(setq org-static-blog-index-length 0)

(setq org-static-blog-use-preview t)

(setq org-static-blog-texts
      '((other-posts
         ("coba" . ""))
        (date-format
         ("coba" . "%Y-%m-%d"))
        (tags
         ("coba" . ""))
        (archive
         ("coba" . ""))
        (posts-tagged
         ("coba" . ""))
        (no-prev-post
         ("coba" . "There is no previous post"))
        (no-next-post
         ("coba" . "There is no next post"))
        (title
         ("coba" . "Title: "))
        (filcobaame
         ("coba" . "Filename: "))))

(setq org-static-blog-langcode "coba")

(setq org-static-blog-page-header (coba-file-content-as-string "morsels/header.html"))

(setq org-static-blog-page-preamble (coba-file-content-as-string "morsels/preamble.html"))

(setq org-static-blog-page-postamble (coba-file-content-as-string "morsels/postamble.html"))

(setq org-static-blog-index-front-matter (coba-file-content-as-string "morsels/root.html"))

(defun org-static-blog-post-preamble (post-filename)
  "Returns the formatted date and headline of the post.
This function is called for every post and prepended to the post body.
Modify this function if you want to change a posts headline."
  (concat
   org-static-blog-post-preamble-text
   "<div class=\"title-with-tags\">\n"
   "<h1 class=\"post-title\">"
   "<a href=\"" (org-static-blog-get-post-url post-filename) "\">"
   (org-static-blog-get-title
    post-filename)
   "</a>"
   "</h1>\n"
   "<div class=\"taglist\">\n"
   (org-static-blog-post-taglist post-filename)
   "</div>\n"
   "</div>\n"
   "<div class=\"post-date\">\n" "~ Posted on: "
   (format-time-string
    (org-static-blog-gettext
     'date-format)
    (org-static-blog-get-date
     post-filename))
   "</div>"))

(defun org-static-blog-post-postamble (post-filename)
  "Returns the tag list and comment box at the end of a post.
This function is called for every post and the returned string is
appended to the post body, and includes the tag list generated by
followed by the HTML code for comments."
  (concat ""
          (if
              (or (string= org-static-blog-post-comments "")
                  (member org-static-blog-no-comments-tag
                          (org-static-blog-get-tags
                           post-filename)))
              ""
            (concat "\n<div id=\"comments\">"
                    org-static-blog-post-comments
                    "</div>"))
          org-static-blog-post-postamble-text))

(defun org-static-blog-assemble-archive ()
  "Re-render the blog archive page.
The archive page contains single-line links and dates for every
blog post, but no post body."
  (let ((archive-filename (concat-to-dir
                           org-static-blog-publish-directory
                           org-static-blog-archive-file))
        (archive-entries nil)
        (post-filenames (org-static-blog-get-post-filenames)))
    (setq post-filenames (sort post-filenames (lambda (x y) (time-less-p
                                                             (org-static-blog-get-date y)
                                                             (org-static-blog-get-date x)))))
    (org-static-blog-with-find-file
     archive-filename
     (org-static-blog-template
      org-static-blog-publish-title
      (concat
       "<ul>\n"
       (apply 'concat (mapcar 'org-static-blog-get-post-summary
                              post-filenames))
       "</ul>\n")))))

(defun org-static-blog-get-post-summary (post-filename &optional
                                                       no-tags)
  "Assemble post summary for an archive page.
This function is called for every post on the archive and
tags-archive page. Modify this function if you want to change an
archive headline."
  (let ((taglist (org-static-blog-post-taglist post-filename)))
    (concat
     "<li>\n"
     "<span class=\"post-date\">\n"
     (format-time-string (org-static-blog-gettext 'date-format)
                         (org-static-blog-get-date post-filename))
     "</span>"
     " ~ <a class=\"post-title-inline\" href=\"" (org-static-blog-get-post-url
                                                  post-filename) "\">"
     (org-static-blog-get-title
      post-filename)
     "</a>\n"
     (unless no-tags
       (when (and taglist (not (string-empty-p taglist)))
         (concat
          "~"
          "<span class=\"taglist\">"
          taglist
          "</span>")))
     "</li>\n")))

(defun org-static-blog-post-taglist (post-filename)
  "Returns the tag list of the post.
This part will be attached at the end of the post, after
the taglist, in a <div id=\"taglist\">...</div> block."
  (let ((taglist-content "")
        (tags
         (remove org-static-blog-no-comments-tag
                 (remove org-static-blog-rss-excluded-tag
                         (org-static-blog-get-tags post-filename)))))
    (when (and tags org-static-blog-enable-tags)
      (setq taglist-content
            (mapconcat (lambda (tag)
                         (concat "\n<a href=\""
                                 (org-static-blog-get-absolute-url (concat "tags.html#" (downcase tag)))
                                 "\">" tag "</a>"))
                       tags "")))
    taglist-content))

(defun org-static-blog-assemble-tags ()
  "Render the tag archive and tag pages."
  (org-static-blog-assemble-tags-archive))

(defun org-static-blog-assemble-tags-archive ()
  "Assemble the blog tag archive page.
The archive page contains single-line links and dates for every
blog post, sorted by tags, but no post body."
  (let ((tags-archive-filename (concat-to-dir
                                org-static-blog-publish-directory
                                org-static-blog-tags-file))
        (tag-tree (org-static-blog-get-tag-tree)))
    (setq tag-tree (sort tag-tree (lambda (x y) (string-greaterp (car y) (car x)))))
    (org-static-blog-with-find-file
     tags-archive-filename
     (org-static-blog-template
      org-static-blog-publish-title
      (concat
       (apply 'concat (mapcar
                       'org-static-blog-assemble-tags-archive-tag
                       tag-tree)))))))

(defun org-static-blog-assemble-tags-archive-tag (tag)
  "Assemble single TAG for all filenames."
  (let ((post-filenames (cdr tag)))
    (setq post-filenames
          (sort post-filenames (lambda (x y) (time-less-p (org-static-blog-get-date x)
                                                          (org-static-blog-get-date y)))))
    (concat "<li>" "<span class=\"tag-title\" id=\"" (downcase (car
                                                                tag))
            "\">" (downcase (car tag))
            "</span>\n<ul>\n"
            (apply 'concat (mapcar '(lambda (post-filenames)
                                      (org-static-blog-get-post-summary
                                       post-filenames 'no-tags))
                                   post-filenames))"</ul>\n</li>")))

(defun org-static-blog-assemble-multipost-page (pub-filename
                                                post-filenames &optional front-matter)
  "Assemble a page that contains multiple posts one after another.
Posts are sorted in descending time."
  (setq post-filenames (sort post-filenames (lambda (x y) (time-less-p (org-static-blog-get-date y)
                                                                       (org-static-blog-get-date x)))))
  (org-static-blog-with-find-file
   pub-filename
   (org-static-blog-template
    org-static-blog-publish-title
    (concat
     (when front-matter front-matter)
     (apply 'concat (mapcar
                     (if org-static-blog-use-preview
                         'org-static-blog-get-preview
                       'org-static-blog-get-post-content)
                     post-filenames))))))

(org-static-blog-publish t)
