#+title: boloñesa
#+date: <2026-03-08 Sun>
#+filetags: food

Some friends asked for a recipe of my ragù alla bolognese[fn:1].

Ingredients:
- 1.5kg of nice quality minced meat, not too fatty, half pork half beef.
- 2kg of nice tomatoes. If you don't have access to fresh tomatoes grown until ripe on the plant, the best bet are canned tomatoes from a nice brand, like anything with a San Marzano DOP. And tomato paste.
- Mirepoix: a sensible amount of carrots, celery and onion. And garlic.
- Red wine that you'd drink.
- Herbs, e.g. parsley rosemary thyme oregano basil, black pepper chilly.

On a +7L pot:
- Heat the pot, add oil.
- Add the *mince* in fistfuls into highish heat, letting each portion cook and develop some color. Stir enough to not let it burn, but let it brown. You want to transfer enough heat to the watery juices to evaporate them quickly , to fry the meat into a caramelized brown crumble instead of boiling it into mushy grey chunks. Some *salt*.
  - If there's time pressure, you can use a second pan to brown the meat faster in parallel.
- Add the *mirepoix*, the *garlic* and the *tomato paste*, and let it cook until translucentish and the tomato paste starts sticking to the bottom of the pot.
- Add ~0.5L of *red wine*, stir to scrub clean the bottom of the pot, and let it reduce down for a bit.
- Add 3/4 of the *tomatoes*. If they are fresh take the woody bits out (and peel them if you don't want to notice the skin cannoli).
- Once it boils reduce to low heat and let it cook for a few hours until it's reduced past the consistency that you want. Add *herbs*. Stir semi frequently, don't let the bottom burn. Careful with the splash.
- Blend and add the remaining 1/4 of *fresh tomatoes*. Nice fresh fruitiness that contrasts with the rich deep flavour of the reduction. Maybe some finely chopped fresh *herbs*. Adjust *salt*; it is more versatile if it's less salty than ideal, you can always add more later.

Bolognese in the fridge, bolognese in the freezer. Bolognese in lasagna with almond-milk bechamel.

[fn:1] xd
