#+title: rip quinoa boy
#+date: <2026-01-26>
#+filetags: food

David Lynch passed away last year. He made a [[https://www.youtube.com/watch?v=uSP-ewdJYJc][video]] going over a quinoa recipe, and in his honor I decided to explore cooking with this grain that I hadn't used a lot before.

My previous perception of quinoa dishes is that they were often bland and meh. But after some exploration I've come to really appreciate two characteristics: a pearl-like consistency that reminds me of pearl couscous or roe, and a subtle nutty flavour.

The key for quinoa to taste nutty is to roast the raw grains on a pan or baking tray until they are fragrant and look toasty, and the key to get the pearl-y texture is to not overcook them. 

- Toast the raw grains on a pan over medium heat, constantly moving them around for a few minutes until they smell nutty.
- Add the same volume of the grains in seasoned water, stir a bit and cover.
- Let it boil and steam at low heat. The goal is for all the water to be absorbed once the grains are ready. You can control the wetness of the mix by uncovering the pan to help more water evaporate, or by adding extra (unseasoned) water if it dries up.
- Once they are just about to have your ideal texuture, take them off the heat and let them rest for a couple minutes.
- Add some fat like butter or olive oil, stir a bit to loosen up the grains, and serve with whatever.
